// quizData.js

export const quizData = {
    letterReading: [
        { question: "Read the letter: E", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: K", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: P", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: L", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: G", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: Y", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: M", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: T", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: X", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the letter: W", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
    ],
    wordReading: [
        { question: "Read the word: go", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: he", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: us", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: cot", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: pin", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: red", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: hut", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: man", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: the", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: boy", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: yes", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: help", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: book", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: day", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: nose", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: who", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: date", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: like", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: rain", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: bird", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: pull", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: mix", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: was", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: slow", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: chair", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
    ],
    rhymeTest: [
        { question: "Choose the word that does not rhyme: cap, map, hop", options: ["cap", "map", "hop"], correctAnswer: "hop" },
        { question: "Choose the word that does not rhyme: rat, pan, fat", options: ["rat", "pan", "fat"], correctAnswer: "pan" },
        { question: "Choose the word that does not rhyme: pig, dig, pin", options: ["pig", "dig", "pin"], correctAnswer: "pin" },
        { question: "Choose the word that does not rhyme: get, pot, dot", options: ["get", "pot", "dot"], correctAnswer: "get" },
        { question: "Choose the word that does not rhyme: bull, pull, mat", options: ["bull", "pull", "mat"], correctAnswer: "mat" },
        { question: "Choose the word that does not rhyme: tab, bud, cab", options: ["tab", "bud", "cab"], correctAnswer: "bud" },
        { question: "Choose the word that does not rhyme: cot, got, toy", options: ["cot", "got", "toy"], correctAnswer: "toy" },
        { question: "Choose the word that does not rhyme: wet, pet, run", options: ["wet", "pet", "run"], correctAnswer: "run" },
        { question: "Choose the word that does not rhyme: cow, dad, how", options: ["cow", "dad", "how"], correctAnswer: "dad" },
        { question: "Choose the word that does not rhyme: hit, fit, lip", options: ["hit", "fit", "lip"], correctAnswer: "lip" },
        { question: "Choose the word that does not rhyme: bun, cup, sun", options: ["bun", "cup", "sun"], correctAnswer: "cup" },
        { question: "Choose the word that does not rhyme: hen, pen, pin", options: ["hen", "pen", "pin"], correctAnswer: "pin" },
    ],
    phonemeReplacement: [
        { question: "Replace /c/ in car with a /b/", options: ["bar", "bat", "cap"], correctAnswer: "bar" },
        { question: "Replace /b/ in boat with a /g/", options: ["goat", "coat", "gate"], correctAnswer: "goat" },
        { question: "Replace /m/ in make with a /c/", options: ["cake", "bake", "fake"], correctAnswer: "cake" },
        { question: "Replace /r/ in red with a /f/", options: ["fed", "bed", "head"], correctAnswer: "fed" },
        { question: "Replace /s/ in sun with a /r/", options: ["run", "ran", "rain"], correctAnswer: "run" },
        { question: "Replace /f/ in fight with a /r/", options: ["right", "rice", "ride"], correctAnswer: "right" },
        { question: "Replace /d/ in down with /br/", options: ["brown", "bride", "brat"], correctAnswer: "brown" },
        { question: "Replace /st/ in stop with /cr/", options: ["crop", "crap", "trap"], correctAnswer: "crop" },
        { question: "Replace /br/ in brick with a /st/", options: ["stick", "stack", "stone"], correctAnswer: "stick" },
        { question: "Replace /n/ in neck with a /ch/", options: ["check", "chip", "chop"], correctAnswer: "check" }
    ],            
    Listening: [
        { question: "Instructions to the Examiner/ Test Administrator: Please read the passage given below for the examinee (child), by following carefully the guidelines provided in Appendix 2 of the manual." , options:["next"] , correctAnswer:"" },
        { question: "Ram and Meena love animals and birds. They have two pets, a dog and a parrot. The dog is named Hero and the parrot is named Mithu.Mithu can make many sounds. He tries to bark like Hero.They often play together.", options:["next"] , correctAnswer:"" },
        { question:"What do Ram and Meena love?" , options: [ "Correct" , "Incorrect" ] , correctAnswer: "Correct" },
        { question:"How many pets do they have?" , options: [ "Correct" , "Incorrect" ] , correctAnswer: "Correct" },
        { question:"Can you name them ?" , options: [ "Correct" , "Incorrect" ] , correctAnswer: "Correct" },
        { question:"What do they do together?" , options: [ "Correct" , "Incorrect" ] , correctAnswer: "Correct" },
        { question:"Which animal would you like as a pet?" , options: [ "Correct" , "Incorrect" ] , correctAnswer: "Correct" },
    ],
    letterWriting:[
        { question: "Write the letter: C", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: G", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: D", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: I", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: F", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: J", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: R", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: Q", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: S", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the letter: V", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
    ],
    wordWriting: [
        { question: "Write the word: cat", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: dog", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: if", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: up", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: pet", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: my", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: tin", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: bed", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: fun", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: out", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: good", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: key", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: ox", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: stop", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: pull", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: tree", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: crow", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: ago", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: them", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Write the word: why", options: ["Correct", "Incorrect"], correctAnswer: "Correct" }
    ],
    Fluency: [
        { question: "Name as many vegetables as you can within 1 minute." }, 
        { question: "Name as many vegetables as you can within 1 minute." },
        { question: "Count number of items named in 1 minute starting with /b/" },
        { question: "Count number of items named in 1 minute starting with /m/" },
    ],
    pictureNaming: {
        images: [
            { image: require('../assets/images/pencil.jpg'), answer: 'apple' },
            { image: require('../assets/images/clock.jpg'), answer: 'banana' },
            { image: require('../assets/images/cup.jpg'), answer: 'cat' },
            { image: require('../assets/images/bird.jpg'), answer: 'apple' },
        ],
    },

    // Other levels can be added here...
};
