export const hindiQuizData = {
    letterReading: [
        { question: "उ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "त", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "भ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ए", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "घ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "य", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ठ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "छ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ह", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "औ", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    wordReading: [
        { question: "एक", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "अब", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "वह", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "झट", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "था", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पलक", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शहर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ताला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "से", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "है", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ऊपर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बाहर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "जंगल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "नील", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "दूध", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "हाथी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "हमारा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "खुश", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "और", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "क्या", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पाँच", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "रूप", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "चित्र", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "नील", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बचपन", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    rhymeTest: [
        { question: "केला मेला लिखा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पवन किरण भवन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "नर सर रस", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पद कद कम", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "केश कोट देश", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "जेब सेब जब", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पानी पीला नानी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "जाग जान भाग", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "सही दही गली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बैल फैल बोल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तुम धुन दुम", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "मोल गोल तोड़", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    phonemeReplacement: [
        { question: " पानी में 'पा' की जगह 'रा' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " गोली में 'गो' की जगह 'मा' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " तारा में 'ता' की जगह 'ही' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " दाना में 'दा' की जगह 'चु' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " छाती में 'छा' की जगह 'मो' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " पीतल में 'पी' की जगह 'बो' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " पायल में 'पा' की जगह 'को' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " ऐनक में 'ऐ' की जगह 'रौ' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " कुल्फ़ी में 'कुल' की जगह 'बर्' ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: " दफ़्तर में 'दफ्' की जगह 'बिस्' बिस्तर ", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    Listening: [
        { question:"एक था राजा । उस का बड़ा महल था। \n राजा ने अपना जन्मदिन मनाया। \n महल को फूलों और दियों से सजाया गया। \n राजा ने नगर में हाथी की सवारी की । \n उसने लोगों में मिठाईयाँ बाँटी । \n राजा और लोगों ने पटाखे जला कर आनंद उठाया।" , options:["अगला"] , correctAnswer:"" },
        { question: "राजा ने क्या मनाया ?", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "महल को कैसे सजाया गया ?", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "राजा ने किस की सवारी की ?", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "राजा ने लोगों में क्या बाँटा ?", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "राजा और लोगों ने कैसे आनंद उठाया ?", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    letterWriting: [
        { question: "ई", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "र", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "व", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "श", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "प", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "म", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ट", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ण", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ध", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ऋ", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    wordWriting: [
        { question: "कर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "इस", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "चख", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "फल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "पवन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "चरण", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "चाचा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तरह", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "समय", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "भी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ने", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "अनार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "फूल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "अपना", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "दिन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "भाई", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "दुख", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बकरी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "मंत्री", options: ["सही", "गलत"], correctAnswer: "सही" },
    ],
    Fluency: [
        { question: "सब्जियों के नाम , एक (1) शमनट के भीतर" }, 
        { question: "जानवरों के नाम , एक (1) शमनट के भीतर" },
        { question: "एक (1) शमनट में नामोच्चारित, हर्दये गए अंश (ध्वनन) से प्रारंभ होनेवाले शब्दों की संख्या।   \n /प्/" },
        { question: "एक (1) शमनट में नामोच्चारित, हर्दये गए अंश (ध्वनन) से प्रारंभ होनेवाले शब्दों की संख्या।   \n /त्/" },
    ],
    pictureNaming: {
        images: [
            { image: require('../assets/images/key.jpg'), answer: 'apple' },
            { image: require('../assets/images/chair.jpg'), answer: 'banana' },
            { image: require('../assets/images/flower.jpg'), answer: 'cat' },
            { image: require('../assets/images/shoe.png'), answer: 'apple' },
        ],
    },
};
