// quizData2.js

export const quizData2 = {
    wordReading: [
        { question: "Read the word: gate", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: comb", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: help", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: seed", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: beach", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: farmer", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: rabbit", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: class", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: train", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: spoon", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: dream", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: clock", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: friend", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: window", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: animal", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: elephant", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: crayon", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: pilot", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: grandmother", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: little", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: picture", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: please", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: money", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: because", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: circus", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: whole", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: beautiful", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: cough", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: listen", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: sure", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: notice", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: request", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: correct", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: brought", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: enough", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: movie", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: accept", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: guest", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: direction", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: beginning", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: heroic", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: sincerely", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: awe", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: together", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: instead", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: erosion", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: moustache", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: mischievous", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: fatigue", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the word: enormous", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
    ],
    rhymeTest: [
        { question: "Choose the word that does not rhyme: cap, map, hop", options: ["cap", "map", "hop"], correctAnswer: "hop" },
        { question: "Choose the word that does not rhyme: rat, pan, fat", options: ["rat", "pan", "fat"], correctAnswer: "pan" },
        { question: "Choose the word that does not rhyme: pig, dig, pin", options: ["pig", "dig", "pin"], correctAnswer: "pin" },
        { question: "Choose the word that does not rhyme: get, pot, dot", options: ["get", "pot", "dot"], correctAnswer: "get" },
        { question: "Choose the word that does not rhyme: bull, pull, mat", options: ["bull", "pull", "mat"], correctAnswer: "mat" },
        { question: "Choose the word that does not rhyme: tab, bud, cab", options: ["tab", "bud", "cab"], correctAnswer: "bud" },
        { question: "Choose the word that does not rhyme: cot, got, toy", options: ["cot", "got", "toy"], correctAnswer: "toy" },
        { question: "Choose the word that does not rhyme: wet, pet, run", options: ["wet", "pet", "run"], correctAnswer: "run" },
        { question: "Choose the word that does not rhyme: cow, dad, how", options: ["cow", "dad", "how"], correctAnswer: "dad" },
        { question: "Choose the word that does not rhyme: hit, fit, lip", options: ["hit", "fit", "lip"], correctAnswer: "lip" },
        { question: "Choose the word that does not rhyme: bun, cup, sun", options: ["bun", "cup", "sun"], correctAnswer: "cup" },
        { question: "Choose the word that does not rhyme: hen, pen, pin", options: ["hen", "pen", "pin"], correctAnswer: "pin" },
    ],    
    phonemeReplacementTest: [
        { question: "Replace /c/ in car with a /b/", options: ["bar", "bat", "cap"], correctAnswer: "bar" },
        { question: "Replace /b/ in boat with a /g/", options: ["goat", "coat", "gate"], correctAnswer: "goat" },
        { question: "Replace /m/ in make with a /c/", options: ["cake", "bake", "fake"], correctAnswer: "cake" },
        { question: "Replace /r/ in red with a /f/", options: ["fed", "bed", "head"], correctAnswer: "fed" },
        { question: "Replace /s/ in sun with a /r/", options: ["run", "ran", "rain"], correctAnswer: "run" },
        { question: "Replace /f/ in fight with a /r/", options: ["right", "rice", "ride"], correctAnswer: "right" },
        { question: "Replace /d/ in down with /br/", options: ["brown", "bride", "brat"], correctAnswer: "brown" },
        { question: "Replace /st/ in stop with /cr/", options: ["crop", "crap", "trap"], correctAnswer: "crop" },
        { question: "Replace /br/ in brick with a /st/", options: ["stick", "stack", "stone"], correctAnswer: "stick" },
        { question: "Replace /n/ in neck with a /ch/", options: ["check", "chip", "chop"], correctAnswer: "check" }
    ],              
    nonwordReadingTest: [
        { question: "Read the nonword: jold", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: hile", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: sheem", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: cade", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: deat", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: barket", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: charden", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: kire", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: hicket", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: thellow", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: mootgall", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: mestinal", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: clower", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: bield", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: pight", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: shrince", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: wickle", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: jundle", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: goked", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: norision", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: delsure", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: gropital", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: cortilary", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: brounkain", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: pluejerries", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: metiance", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: baughder", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: phlength", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: semicious", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: knayrudge", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "Read the nonword: pneufolia", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
    ],    
    listening: [
        { question: `Puja looked out of the window. She said, “It is sunny. It is warm. There is a breeze. It is a perfect day to fly a kite!” Puja called to her brother Amit, “Get your shoes on. Today you will learn to fly a kite!” Puja went to the garage and got her kite. It was red and white. “We need room to run. We will go to the park,” Puja said to Amit. “Yippee! I love to run!” shouted Amit. Puja told Amit, “I will tell you what to do. First, hold the kite up. The end with the string faces down. Next, hold the bottom of the kite in one hand. Hold the string with your other hand. Last, run! Let go of the kite and keep holding the string.” They both gave it a try. “Run, run, run!” yelled Amit. “Up, up, up, it goes!” “Now it is in the sky,” said Puja. “Now we hold the string and let it fly high! When it is time to go, we will pull the kite down.” “I love flying a kite,” said Amit. “I love flying a kite too,” said Puja. “This is the way we fly a kite!” they both cheered.` , options:["next"] , correctAnswer:"" },
            {question: "How many people are in the story?",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
            {question: "What are their names?",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
            {question: "How do they know each other?",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
            {question: "How was the weather?",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
            {question: "What activity did they plan to do?",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
            {question: "Write a few lines on kites.",options: ["Answered", "Not Answered"],correctAnswer: "Answered"},
    ],
    fluency: [
        { question: "Name as many vegetables as you can within 1 minute." }, 
        { question: "Name as many fruits as you can within 1 minute." },
        { question: "Say letters with /b/ within 1 minute" },
        { question: "Say letters with /m/ within 1 minute" },
    ],
    spellingTest: [
        { question: "kite", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "hold", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "shade", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "road", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "the", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "was", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "sheet", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "breeze", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "string", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "window", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "family", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "violet", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "garage", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "cheered", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "scream", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "used", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "knowledge", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "farmhouse", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "photograph", options: ["Correct", "Incorrect"], correctAnswer: "Correct" },
        { question: "adaptation", options: ["Correct", "Incorrect"], correctAnswer: "Correct" }
    ],    
    pictureNaming: {
        images: [
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
            { image: require('../assets/images/banana.jpg'), answer: 'banana' },
            { image: require('../assets/images/Cat.jpg'), answer: 'cat' },
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
        ],
    },
    // Other levels can be added here...
};
