export const teluguQuizData = {
    letterReading: [
        { question: "ఈ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఉ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఎ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "క", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "న", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "మ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "య", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "హ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    wordReading: [
        { question: "అల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఏట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "తల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఆట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఐన", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "దగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఇల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "బర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఓడ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈత", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "కళ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గద", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "రమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఊడ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పనస", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "వచన", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "వలస", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గడప", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పలక", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    rhymeTest: [
        { question: "నయ	లయ	కథ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఎర	బర	గద", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "షమ అల తల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నగ	దగ ఆట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఎర	పగ వర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఆట	రమ ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఓడ	జడ పగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "బర	వర నయ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "దయ	పగ దగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "క్షమ తల రమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "దయ	లయ వర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈగ	నగ ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    phonemeReplacement: [
        { question: " ఈగ లోని 'ఈ' ని 'న' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " నర లోని 'న' ని 'వ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " తల లోని 'త' ని 'అ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " నగ లోని 'న' ని 'ప' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " ఓడ లోని 'ఓ' ని 'జ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " రమ లోని 'ర' ని 'ఉ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " బర లోని 'బ' ని 'ఎ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " దయ లోని 'ద' ని 'ల' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " ఎర లోని 'ఎ' ని 'వ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: " జడ లోని 'జ' ని 'వ' తో మార్చండి ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    Listening: [
        { question:" ఒక చిన్న కోడిపిల్ల పిచ్చుకతో ఆడుకుంటూ ఉంది. \n అది పొలంలో దూకుతూ సంతోషంగా ఉంది. \n ఒక్కసారిగా ఆకాశంలో మేఘాలు కనిపించాయి. \n కోడిపిల్ల భయపడి తల్లి దగ్గరకు పరుగెత్తింది. \n తల్లి చెప్పింది, భయపడకు, ఇవి వర్షం ముందు వచ్చే మేఘాలు మాత్రమే.\n కోడిపిల్ల తల్లితో సంతోషంగా ఉన్నది." , options:["अगला"] , correctAnswer:"" },
        { question: "కోడిపిల్ల ఎవరితో ఆడుతోంది?", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఆకాశంలో ఏమి కనిపించాయి?", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "కోడిపిల్ల ఎక్కడికి పరుగెత్తింది?", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "తల్లి కోడిపిల్లకు ఏమి చెప్పింది?", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "మీకు ఏ పక్షి అంటే ఇష్టం?", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    letterWriting: [
        { question: "ఈ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఒ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "క", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "చ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ద", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "డ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "వ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "శ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "స", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    wordWriting: [
        { question: "అల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఏట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "తల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఆట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఐన", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "దగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఇల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "బర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఓడ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈత", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఈల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "కళ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గద", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "రమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఊడ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    Fluency: [
        { question: "ఇచ్చిన శబ్దం (అక్షరం) తో ప్రారంభమయ్యే పదాలను పిల్లవాడు ఒక్క నిమిషంలో ఎన్ని చెప్పాడో లెక్కించండి. \n  /బ/" }, 
        { question: "ఇచ్చిన శబ్దం (అక్షరం) తో ప్రారంభమయ్యే పదాలను పిల్లవాడు ఒక్క నిమిషంలో ఎన్ని చెప్పాడో లెక్కించండి. \n  /గ/" },
        { question: "ఒక్క నిమిషంలో పిల్లవాడు గుర్తించిన అంశాల సంఖ్యను లెక్కించండి. \n జంతువుల పేర్లు తెలపండి" },
        { question: "ఒక్క నిమిషంలో పిల్లవాడు గుర్తించిన అంశాల సంఖ్యను లెక్కించండి. \n వాహనాల పేర్లు తెలపండి" },
    ],
    pictureNaming: {
        images: [
            { image: require('../assets/images/key.jpg'), answer: 'apple' },
            { image: require('../assets/images/chair.jpg'), answer: 'banana' },
            { image: require('../assets/images/flower.jpg'), answer: 'cat' },
            { image: require('../assets/images/shoe.png'), answer: 'apple' },
        ],
    },
};
