// quizData2.js

export const hindiQuizData2 = {
    wordReading: [
        { question: "शब्द पढ़ें: पवन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: मटर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: अनार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: खेत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: चोट", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: खीरा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: चूरण", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: ऐब", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: मेला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: रोटी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: साबुन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: रूई", options: ["सही", "गलत"], correctAnswer: "सही" }, 
        { question: "शब्द पढ़ें: क्रकियां", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: तक्रिया", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: पहिया", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: नेत्र", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: यज्ञ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: ऋतु", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: मुरली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: टोकरी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: बैला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: कौआ", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: लौकी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: बबल्ली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: अभ्यास", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: गड़बड़", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: उपयोग", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: इंटिहा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: सृजन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: बस्तर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: दृश्य", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: ज्वाला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: दल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: वेवचन", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: हरियाली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: चमत्कार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: अपेक्षा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: युद्ध", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: स्वास्थ्य", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: प्रार्थना", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: अंग्रेज़ी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: प्रशंसा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: निर्णय", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: अत्याचार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: प्रसिद्ध", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: उपस्थित", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: नक्शाचंत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: तृष्णा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: दानकारी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शब्द पढ़ें: कुरुक्षेत्र", options: ["सही", "गलत"], correctAnswer: "सही" }
    ],
    rhymeTest: [
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: केला, मेला, शलखा", options: ["केला", "मेला", "शलखा"], correctAnswer: "शलखा" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: पवन, क्रकरण, भवन", options: ["पवन", "क्रकरण", "भवन"], correctAnswer: "क्रकरण" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: नर, शर, रि", options: ["नर", "शर", "रि"], correctAnswer: "रि" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: पर्दा, कर्द, कम", options: ["पर्दा", "कर्द", "कम"], correctAnswer: "कम" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: के, श, कोट, र्देश", options: ["के", "श", "कोट", "र्देश"], correctAnswer: "र्देश" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: वेब, वेब, वेब", options: ["वेब", "वेब", "वेब"], correctAnswer: "वेब" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: पानी, पीला, नानी", options: ["पानी", "पीला", "नानी"], correctAnswer: "पीला" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: भाग, भाग, भाग", options: ["भाग", "भाग", "भाग"], correctAnswer: "भाग" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: ही, धि, गली", options: ["ही", "धि", "गली"], correctAnswer: "गली" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: बैल, बैल, बोल", options: ["बैल", "बैल", "बोल"], correctAnswer: "बोल" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: तुम, तुम, तुम", options: ["तुम", "तुम", "तुम"], correctAnswer: "तुम" },
        { question: "वह शब्द चुनें जिसमें तुकबंदी नहीं है: मोल, गोल, तोड", options: ["मोल", "गोल", "तोड"], correctAnswer: "तोड" }
    ],      
    phonemeReplacementTest: [
        { question: "पानी में 'पा' की िगह 'रा'", options: ["रानी", "मानी", "वानी"], correctAnswer: "रानी" },
        { question: "गोली में 'गो' की िगह 'मा", options: ["माली", "मोटी", "गाली"], correctAnswer: "माली" },
        { question: " तारा में 'ता' की िगह 'ही'", options: ["हीरा", "हारा", "तारा"], correctAnswer: "हीरा" },
        { question: "र्दाना में 'र्दा' की िगह 'च'", options: ["चुना", "चुका", "चुती"], correctAnswer: "चुना" },
        { question: "छाती में 'छा' की िगह 'मो' ", options: ["मोती", "मोटी", "मोल"], correctAnswer: "मोती" },
        { question: "पीतल में 'पी' की िगह 'बो'", options: ["बोतल", "बोटी", "बोला"], correctAnswer: "बोतल" },
        { question: "पायल में 'पा' की िगह 'को'", options: ["कोयल", "कोला", "कोरा"], correctAnswer: "कोयल" },
        { question: "ऐनक में 'ऐ' की िगह 'रौ'", options: ["रौनक", "रौंड", "रौन"], correctAnswer: "रौनक" },
        { question: "कल्फ़ी में 'कल' ् की िगह 'बर", options: ["बफ़़ी", "बर्फ़ी", "बड़ी"], correctAnswer: "बफ़़ी" },
        { question: "र्दफ़्तर में 'र्दि्' की िगह 'बबि'", options: ["बबस्तर", "बब्बर", "बब", "बब्बी"], correctAnswer: "बबस्तर" }
    ],            
    nonwordReadingTest: [
        { question: "तनरर्थक शधद पढ़ें: शनर्द", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: गािर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: खेब", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: कोतल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: ऐझक", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: िूल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: यालू", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: र्दारे", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: किाया", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: चपीना", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: ला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: मु", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: रछली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: चौिम", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: नतपली", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: िैधिक", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: वंिा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: िवथत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: णखमौरा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: हश्मा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: रेग", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: शमचटारी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: लर्रीचा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: गहायरा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: नामीप", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: पुरी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: मक्न्र्दल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: िुब्बारा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: रौक्ष्टत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: ग्रज्वशलक", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: शु्ख्यतंत्री", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "तनरर्थक शधद पढ़ें: र्दु वपथयाँ", options: ["सही", "गलत"], correctAnswer: "सही" }
    ],       
    listening: [
        { question: `उत्तरी हवा और िूरि इि बात पर झगड रहे र्े, क्रक हम र्दोनों में ज़्यार्दा बलवान कौन है l इतने में गरम चोगा पहने एक मुिाक्रिर उिर आ ननकला l हवा और िूरि र्दोनों इि बात पर रािी हो गए क्रक र्दोनो में िे िो पहले मुिाक्रिर का चोगा उतरवा र्देगा, वही ज़्यार्दा बलवान िमझा िाएगा l इि पर उत्तरी हवा अपना पूरा ज़ोर लगाकर चलने लगी l लेक्रकन वो िैिे - िैिे अपना ज़ोर बढ़ाती गई, वैिे – वैिे मुिाक्रिर अपने बर्दन पे चोगे को और भी किकर लपेटता गया I अंत में हवा ने कोशशश बंर्द कर र्दी l क्रिर िूरि तेज़ी के िार् ननकला और मुिाक्रिर ने तुरंत अपना चोगा उतार हर्दया l इिशलए हवा को मानना पडा क्रक उन र्दोनो में िूरि ही ज़्यार्दा बलवान है l`, options: ["next"], correctAnswer: "" },
        { question: "कहानी में क्रकतने लोग हैं?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" },
        { question: "उनके सया नाम हैं?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" },
        { question: "उन्होनें अपना झगडा कै िे हल क्रकया?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" },
        { question: "मुिाक्रिर ने सया पहना र्ा?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" },
        { question: "अंत में कौन िीता?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" },
        { question: "कहानी में झगडा क्रकि बात पर कर रहे हैं?", options: ["उत्तर दिया", "उत्तर नहीं दिया"], correctAnswer: "उत्तर" }
    ],    
    fluency: [
        { question: "सब्जियों के नाम , एक (1) शमनट के भीतर" }, 
        { question: "जानवरों के नाम , एक (1) शमनट के भीतर" },
        { question: "एक (1) शमनट में नामोच्चारित, हर्दये गए अंश (ध्वनन) से प्रारंभ होनेवाले शब्दों की संख्या।   \n /प/" },
        { question: "एक (1) शमनट में नामोच्चारित, हर्दये गए अंश (ध्वनन) से प्रारंभ होनेवाले शब्दों की संख्या।   \n /त/" },
    ],
    spellingTest: [
        { question: "उपहार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "क्रिर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "हार्ी", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "शमत्र", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "प्रकार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "प्यार", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "मेहनत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "कोई", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बहुत", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "कोशशश", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "मक्ुश्कल", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "हँिना", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "िरूि", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बलवान", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "बंर्द", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "हवा", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "िोर", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "ननकला", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "कतथव्य", options: ["सही", "गलत"], correctAnswer: "सही" },
        { question: "िैिा", options: ["सही", "गलत"], correctAnswer: "सही" }
    ],    
    pictureNaming: {
        images: [
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
            { image: require('../assets/images/banana.jpg'), answer: 'banana' },
            { image: require('../assets/images/Cat.jpg'), answer: 'cat' },
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
        ],
    },
    // Other levels can be added here...
};
