// quizData2.js

export const teluguQuizData2 = {
    wordReading: [
        { question: "పదం చదవండి : పక్షి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పంట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : చెట్టు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : ఆకాశం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : తీపి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కాలం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బాలిక", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : సీత", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బాలుడు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : ఆవు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : గోరు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : నది", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కలం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పువ్వు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కొండ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బల్లి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కబురు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పసుపు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బల్లం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పండుగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బాలబాలిక", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పన్ను", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : చంద్రుడు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : నక్షత్రం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : జంతువు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : రాముడు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కుటుంబం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కుతూహలము", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : సూర్యుడు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : మిత్రం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పండగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : సముద్రం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : సరైనది", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : ఉత్సవం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పసిపిట్ట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : గురువు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : స్నేహం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పల్లకీ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కప్ప", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : జలపాతం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : కొబ్బరికాయ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : మూల్యం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : గ్రీష్మం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : వర్షం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : పుస్తకం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : సప్తమి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : స్నేహితులు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : బలవంతం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : లక్ష్యం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : గమనిక", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పదం చదవండి : గృహం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],
    rhymeTest: [
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  నయ	లయ కథ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  ఎర	బర	గద", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి: షమ అల తల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి: నగ దగ ఆట", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి: ఎర పగ వర	", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  ఆట రమ ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  ఓడ	జడ	పగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  బర	వర	నయ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  దయ	పగ	దగ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  క్షమ తల	రమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  దయ	లయ	వర", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రాస లేని పదాన్ని ఎంచుకోండి:  ఈగ	నగ	ఉమ", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],    
    phonemeReplacementTest: [
        { question: "ఈగ లోని 'ఈ' ని 'న' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నర లోని 'న' ని 'వ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "తల లోని 'త' ని 'అ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నగ లోని 'న' ని 'ప' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఓడ లోని 'ఓ' ని 'జ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "రమ లోని 'ర' ని 'ఉ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "బర లోని 'బ' ని 'ఎ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "దయ లోని 'ద' ని 'ల' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఎర లోని 'ఎ' ని 'వ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "జడ లోని 'జ' ని 'వ' తో మార్చండి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" }
    ],              
    nonwordReadingTest: [
        { question: "అర్ధరహిత పదాలు చదవండి : గునిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : బురసి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : నుపరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : రిమిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : నితరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : గులసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : మునిప", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : టుమసి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : సుమరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : నిపలా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : గుటిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : టినిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : లిమసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : జుతరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : రిపలా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : ఫిమసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : మోనసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : మిపలా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : సులని", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : టునిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : బుటసి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : జులమి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : దిమల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : రిమపి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : బుటరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : లిపసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : సిమరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : టుమిల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : నిలసా", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "అర్ధరహిత పదాలు చదవండి : గుమరి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
    ],    
    listening: [
        { question: `సితార అనే ఒక చిన్న అమ్మాయి "కొండపల్లి" అనే ఒక గ్రామంలో ఉండేది. ఆమెకు అడవిలో తిరగడం చాలా ఇష్టం. ఒక రోజు, సితార కొండపల్లి గ్రామం నుండి అడవిలోకి వెళ్ళింది. అడవిలో ఆమె అనేక చెట్లు, పంటలు, పక్షులు చూసింది. అడవి చాలా అందంగా, శాంతంగా ఉండేది. పచ్చని చెట్లు, రంగు రంగుల పుష్పాలు, పక్షుల గీతాలు అడవిని మరింత అందంగా మార్చాయి.
అది మధ్యాహ్న సమయం. సితార ఆహారం తీసుకొని అడవిలో మరింత లోతుగా వెళ్లింది. అప్పుడు ఆమె ఒక చిన్న జింకను చూసింది. ఆ జింక సితారను చూసి త్వరగా పారిపోయింది. సితార ఆ జింకను వెంబడించి పరుగెత్తింది. కానీ జింక చాలా వేగంగా పరుగెత్తింది, సితార దాన్ని పట్టుకోలేకపోయింది.
అయినప్పటికీ సితార నిరాశ పడలేదు. ఆమె అడవిలో మరిన్ని జంతువులను, పక్షులను చూసి ఎంతో ఆనందపడింది. ఆమె అడవిలో ఆనందంగా గడిపిన తరువాత, ఇంటికి తిరిగి వచ్చింది.
` , options:["next"] , correctAnswer:"" },
            {question: "సితార ఎక్కడ ఉండేది ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
            {question: "ఆమెకు ఏది ఇష్టం ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
            {question: "ఒక రోజు సితార ఎక్కడ వెళ్ళింది ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
            {question: "జింక సితారను చూసి ఏమి చేసింది ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
            {question: "సితార జింకను పట్టుకోగలిగిందా ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
            {question: "అడవి ఎలా ఉంది ?",options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది"},
    ],
    fluency: [
        { question: "ఇచ్చిన శబ్దం (అక్షరం) తో ప్రారంభమయ్యే పదాలను పిల్లవాడు ఒక్క నిమిషంలో ఎన్ని చెప్పాడో లెక్కించండి. \n  /బ/" }, 
        { question: "ఇచ్చిన శబ్దం (అక్షరం) తో ప్రారంభమయ్యే పదాలను పిల్లవాడు ఒక్క నిమిషంలో ఎన్ని చెప్పాడో లెక్కించండి. \n  /గ/" },
        { question: "ఒక్క నిమిషంలో పిల్లవాడు గుర్తించిన అంశాల సంఖ్యను లెక్కించండి. \n జంతువుల పేర్లు తెలపండి" },
        { question: "ఒక్క నిమిషంలో పిల్లవాడు గుర్తించిన అంశాల సంఖ్యను లెక్కించండి. \n వాహనాల పేర్లు తెలపండి" },
    ],
    spellingTest: [
        { question: "శాంతి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "నది", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పట్టణం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "వెన్నెల", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పసుపు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గమన౦", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "వేతన౦", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఆకాశం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "కనకం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ఉదయం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "మేళం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గాలి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పాటలు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "చంటి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ప్రగతి", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "చిలుక", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "ముంచు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "గ్రామం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "పుస్తకం", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" },
        { question: "మనసు", options: ["సరైనది", "తప్పు"], correctAnswer: "సరైనది" }
    ],    
    pictureNaming: {
        images: [
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
            { image: require('../assets/images/banana.jpg'), answer: 'banana' },
            { image: require('../assets/images/Cat.jpg'), answer: 'cat' },
            { image: require('../assets/images/apple.jpg'), answer: 'apple' },
        ],
    },
    // Other levels can be added here...
};
